import type { Case, Exchange, NoticeType } from '../../types'

/** Pre-filled, editable document bodies for the three lawful-action cards — freeform copy in
 * the project's tone (per the source spec), not legal advice: every draft carries its own
 * "for officer review" framing rather than presenting itself as ready to file. */
export function noticeBody(type: NoticeType, caseData: Case, exchange: Exchange): string {
  switch (type) {
    case 'exchange-request':
      return `To: Compliance Team, ${exchange.name}
Re: Request for KYC details and account freeze — Case ${caseData.id}

We are investigating a cyber fraud complaint (NCRP ${caseData.ncrp}) in which traced funds reached a deposit address under your platform's control: ${exchange.depositAddr}.

We request that you:
  1. Preserve all KYC/KYB records associated with this deposit address.
  2. Freeze any balance held against this address pending further legal process.
  3. Provide the transaction history for this address covering the period around ${caseData.incidentAt}.

A formal notice will follow through appropriate legal channels. Please treat this as an urgent preservation request in the interim.

— Cyber Crime Cell, ${caseData.location}`

    case 'bnss-notice':
      return `NOTICE UNDER SECTION 94, BHARATIYA NAGARIK SURAKSHA SANHITA, 2023
(Summons to produce documents — formerly Section 91, Code of Criminal Procedure, 1973)

In the matter of: Case ${caseData.id} (NCRP ${caseData.ncrp})
To: ${exchange.name}, ${exchange.jurisdiction}

You are hereby directed to produce all documents, records, and account information relating to deposit address ${exchange.depositAddr}, in connection with the investigation of the above-referenced complaint registered at ${caseData.location}.

Produce the above within the period prescribed by law. Failure to comply without lawful excuse may attract consequences under applicable law.

[DRAFT — for officer review and signature before issue. Not a final legal instrument.]`

    case 'fiu-report':
      return `TO: Financial Intelligence Unit – India (FIU-IND)
SUBJECT: Suspicious activity report — unregistered virtual asset service provider

This report flags ${exchange.name} (${exchange.jurisdiction}), a virtual asset service provider observed servicing an estimated ${exchange.indianUsers} Indian users despite not being registered with FIU-IND.

Deposit address ${exchange.depositAddr} received proceeds traced from cyber fraud case ${caseData.id} (NCRP ${caseData.ncrp}). Supporting trace evidence is attached in the accompanying investigation report.

Generated by KAIZEN v1.0.`
  }
}
